import { createLab, recordTrial, setConclusion, setPrediction } from './mass-model.js';

const I18N = {
  zh: { back:'返回平台', title:'质量守恒实验室', missionNav:'任务', benchNav:'实验台', notebookNav:'记录册', missionTitle:'气泡跑掉了，质量去哪儿了？', missionIntro:'先猜一猜，再让天平留下两张对照证据。', predictionTitle:'留下预测', predictionLost:'气泡跑掉，质量消失', predictionKept:'只要全都称到，质量还在', vesselTitle:'选一个装置', vesselHint:'从敞口开始，再给第二杯盖上透明罩。', open:'敞口烧杯', openHint:'气体可以飞走', sealed:'密闭罩', sealedHint:'每样东西都留在罩里', run:'倒入醋，开始称量', hint:'给我一点提示', hintText:'天平只会称到放在它上面的东西。看看气泡有没有离开系统。', reset:'重新实验', benchTitle:'天平正在看着每一克', ready:'准备就绪', reactionLabel:'醋 + 小苏打', before:'反应前', after:'反应后', benchReady:'选好装置，倒入醋，看气泡和读数一起变化。', modelNote:'教学示意：气泡代表二氧化碳；真实实验请在教师指导下进行。', notebookTitle:'把两次称量放在一起', tableVessel:'装置', tableBefore:'前 / g', tableAfter:'后 / g', tableGas:'逸出 CO₂ / g', empty:'先完成第一杯实验。', conclusionTitle:'说出证据支持的结论', conclusionHint:'两杯都做完后再选。错了也能立刻换一个。', conclusionLost:'反应让质量消失了', conclusionConserved:'把所有物质算进来，总质量不变', complete:'密闭罩把“跑掉的”质量找回来了！', soundOn:'关闭声音', soundOff:'打开声音', theme:'切换主题', lang:'Switch to English', choosePrediction:'先留下一条预测，再做实验。', duplicate:'这杯已经记录过了。换另一个装置来做对照。', openDone:'敞口杯变轻了：4.0 g 的气泡飞出了天平。把密闭罩也做一次！', sealedDone:'密闭罩还是 100.0 g：气泡没有离开称量系统。去比较两条记录。', wrongConclusion:'气泡没有消失，只是离开了敞口烧杯。试试把所有物质算进去。', rightConclusion:'对！敞口读数变轻是因为 CO₂ 离开了天平；密闭系统中反应前后总质量不变。', resetDone:'实验已清空。重新猜想，再让两只杯子说话。', reacting:'正在起泡…' },
  en: { back:'Back to platform', title:'Mass Conservation Lab', missionNav:'Mission', benchNav:'Bench', notebookNav:'Notebook', missionTitle:'The bubbles escaped. Where did the mass go?', missionIntro:'Make a prediction, then let the balance collect two pieces of evidence.', predictionTitle:'Make a prediction', predictionLost:'Bubbles escape, so mass disappears', predictionKept:'If we weigh everything, mass remains', vesselTitle:'Choose a vessel', vesselHint:'Start open, then place a clear dome over the second cup.', open:'Open beaker', openHint:'Gas can fly away', sealed:'Sealed dome', sealedHint:'Everything stays inside', run:'Pour vinegar and weigh', hint:'Give me a hint', hintText:'A balance only weighs what is sitting on it. Watch whether bubbles leave the system.', reset:'Restart experiment', benchTitle:'The balance watches every gram', ready:'Ready', reactionLabel:'vinegar + baking soda', before:'Before', after:'After', benchReady:'Choose a vessel, pour in vinegar, and watch bubbles and the reading change together.', modelNote:'Teaching model: bubbles represent carbon dioxide. Do real experiments with a teacher.', notebookTitle:'Put the two weighings together', tableVessel:'Vessel', tableBefore:'Before / g', tableAfter:'After / g', tableGas:'Escaped CO₂ / g', empty:'Finish the first cup first.', conclusionTitle:'State the conclusion supported by evidence', conclusionHint:'Choose after both cups. A wrong answer can be changed right away.', conclusionLost:'The reaction made mass disappear', conclusionConserved:'When all substances are counted, total mass stays the same', complete:'The sealed dome found the “escaped” mass!', soundOn:'Mute sound', soundOff:'Turn sound on', theme:'Toggle theme', lang:'切换到中文', choosePrediction:'Make a prediction before running the experiment.', duplicate:'This cup is already logged. Use the other vessel for a comparison.', openDone:'The open cup got lighter: 4.0 g of bubbles left the balance. Try the sealed dome too!', sealedDone:'The sealed dome is still 100.0 g: the bubbles stayed in the weighed system. Compare both records.', wrongConclusion:'The bubbles did not disappear; they left the open beaker. Count every substance.', rightConclusion:'Yes! The open reading falls because CO₂ leaves the balance. In a sealed system, total mass is equal before and after.', resetDone:'Experiment cleared. Predict again, then let both cups speak.', reacting:'Fizzing…' },
};
const $ = (s) => document.querySelector(s);
const STORE = 'kidslab.mass-conservation-lab';
const SOUND = 'kidslab.mass-conservation-lab.sound';
const els = { app:$('#app'), scene:$('#scene'), feedback:$('#feedback'), phase:$('#phaseBadge'), scale:$('#scaleReading'), after:$('#afterReading'), note:$('#benchNote'), rows:$('#trialRows'), count:$('#trialCount'), conclusion:$('#conclusionStatus'), complete:$('#completeCard'), hint:$('#hintText'), sound:$('#soundBtn') };
let lang = window.cool?.preferences?.lang || 'zh'; let lab = load() || createLab(); let selected = 'open'; let muted = localStorage.getItem(SOUND) === 'off'; let audio; let running = false;
const t = (key) => I18N[lang][key] || key;
function load(){ try { const saved=JSON.parse(localStorage.getItem(STORE)); return saved?.trials ? saved : null; } catch { return null; } }
function save(){ try { localStorage.setItem(STORE,JSON.stringify(lab)); } catch {} }
function tone(kind){ if(muted) return; try { audio ||= new AudioContext(); const o=audio.createOscillator(), g=audio.createGain(); const now=audio.currentTime; o.frequency.value=kind==='good'?660:kind==='bad'?150:370; g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.1,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.22); o.connect(g).connect(audio.destination); o.start(now); o.stop(now+.24); } catch {} }
function message(key, kind=''){ els.feedback.textContent=t(key); els.feedback.className=`feedback ${kind}`; }
function format(v){ return `${Number(v).toFixed(1)} g`; }
function render(){
  document.title=`⚗️ ${t('title')} · KidsLab`; document.documentElement.lang=lang==='zh'?'zh-CN':'en';
  document.querySelectorAll('[data-t]').forEach((node)=>{node.textContent=t(node.dataset.t);});
  document.querySelectorAll('[data-prediction]').forEach((b)=>b.classList.toggle('is-selected',lab.prediction===b.dataset.prediction));
  document.querySelectorAll('[data-vessel]').forEach((b)=>b.classList.toggle('is-selected',selected===b.dataset.vessel));
  els.scene.dataset.vessel=selected; els.sound.textContent=muted?'🔇':'🔊'; els.sound.setAttribute('aria-pressed',String(muted)); els.sound.setAttribute('aria-label',t(muted?'soundOff':'soundOn'));
  els.count.textContent=`${lab.trials.length} / 2`; els.rows.innerHTML=lab.trials.length ? lab.trials.map((r)=>`<tr><td>${t(r.vessel)}</td><td>${format(r.massBeforeG)}</td><td>${format(r.massAfterG)}</td><td>${r.escapedGasG ? format(r.escapedGasG) : '—'}</td></tr>`).join('') : `<tr><td colspan="4">${t('empty')}</td></tr>`;
  const ready=lab.trials.length===2; $('#runBtn').disabled=running; $('#conclusionLost').disabled=!ready; $('#conclusionConserved').disabled=!ready; els.complete.hidden=lab.phase!=='complete';
  if(lab.phase==='complete'){els.phase.textContent='✓'; els.conclusion.textContent=t('rightConclusion'); els.conclusion.className='conclusion is-good';}
  else if(ready) els.phase.textContent='2 / 2'; else els.phase.textContent=t('ready');
}
function run(){
  if(running) return;
  if(!lab.prediction){message('choosePrediction','is-bad');tone('bad');return;}
  const result=recordTrial(lab,selected); if(!result.ok){message(result.reason==='duplicate-trial'?'duplicate':'choosePrediction','is-bad');tone('bad');return;}
  running=true; render(); els.scene.classList.add('is-reacting'); els.phase.textContent=t('reacting'); setTimeout(()=>{lab=result.lab; running=false; save(); els.scale.textContent=Number(result.lab.trials.at(-1).massAfterG).toFixed(1); els.after.textContent=format(result.lab.trials.at(-1).massAfterG); els.note.textContent=t(selected==='open'?'openDone':'sealedDone'); message(selected==='open'?'openDone':'sealedDone','is-good'); tone('good'); render();},560);
}
function selectConclusion(value){const result=setConclusion(lab,value); lab=result.lab; save(); if(result.ok){message('rightConclusion','is-good');tone('good');window.cool?.stage('level2');window.cool?.complete?.();window.cool?.track('compare-systems');}else{els.conclusion.textContent=t('wrongConclusion');els.conclusion.className='conclusion is-bad';tone('bad');}render();}
document.querySelectorAll('[data-prediction]').forEach((b)=>b.addEventListener('click',()=>{lab=setPrediction(lab,b.dataset.prediction).lab;save();message('choosePrediction','is-good');tone('tap');render();}));
document.querySelectorAll('[data-vessel]').forEach((b)=>b.addEventListener('click',()=>{selected=b.dataset.vessel;els.after.textContent='—';els.scale.textContent='100.0';render();}));
$('#runBtn').addEventListener('click',run); document.querySelectorAll('[data-conclusion]').forEach((b)=>b.addEventListener('click',()=>selectConclusion(b.dataset.conclusion)));
$('#resetBtn').addEventListener('click',()=>{lab=createLab();selected='open';running=false;try{localStorage.removeItem(STORE);localStorage.removeItem('kidslab.progress.mass-conservation-lab');}catch{}els.after.textContent='—';els.scale.textContent='100.0';message('resetDone','is-good');render();});
$('#hintBtn').addEventListener('click',()=>{const show=els.hint.hidden;els.hint.hidden=!show;$('#hintBtn').setAttribute('aria-expanded',String(show));});
els.sound.addEventListener('click',()=>{muted=!muted;try{localStorage.setItem(SOUND,muted?'off':'on')}catch{}render();});
$('#langBtn').addEventListener('click',()=>{window.cool?.preferences?.setLang?.(lang==='zh'?'en':'zh');}); $('#themeBtn').addEventListener('click',()=>window.cool?.preferences?.toggleTheme?.());
addEventListener('langchange',(e)=>{lang=e.detail?.lang||window.cool?.preferences?.lang||lang;render();}); addEventListener('themechange',render);
document.querySelectorAll('.mobile-nav button').forEach((b)=>b.addEventListener('click',()=>{const p=b.dataset.panel;els.app.dataset.mobilePanel=p;document.querySelectorAll('.mobile-nav button').forEach((x)=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-section]').forEach((x)=>x.classList.toggle('is-active',x.dataset.section===p));}));
document.querySelector(`[data-section="${els.app.dataset.mobilePanel}"]`)?.classList.add('is-active'); render();
